service: sls-firstAppExpress

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1

functions:
  app:
    handler: app.handler
    events:
      - http:
          path: '/'
          method: ANY
          cors: true
      - http:
          path: '{proxy+}'
          method: ANY
          cors: true
  fun:
    handler: routes/fun.handler
    events:
      - http:
          path: 'fun/{proxy+}'
          method: GET
          cors: true
      - http:
          path: 'fun/'
          method: POST
          cors: true
      - http:
          path: 'fun/'
          method: PUT
          cors: true
      - http:
          path: 'fun/{proxy+}'
          method: DELETE
          cors: true